/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package triangulosExamen;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import static javax.swing.SpringLayout.HEIGHT;

/**
 *
 * @author ESFOT
 */
public class GUIExamen extends javax.swing.JFrame {

   
    ArrayList<figuras> listaTriangulos = new ArrayList();
    DefaultComboBoxModel modeloComboBox = new DefaultComboBoxModel();
    boolean siEsTriangulo = false;
    
    public GUIExamen() {
        initComponents();
        
        String[] listaTriangulos = new String[]{"Rectangulo","Isosceles","Escaleno","Equilatero"};
        
        //Ingreso el modelo del combo
        for(int i = 0; i < listaTriangulos.length; i++){
            
            modeloComboBox.addElement(listaTriangulos[i]);
        }
        comboTriangulos.setModel(modeloComboBox);
        
       panelComprobacion(false);
    //int iconoAviso = JOptionPane.INFORMATION_MESSAGE;
    //JOptionPane.showMessageDialog(rootPane, "Ahora verifiquemos si es un triángulo ", "AVISO", iconoAviso);

            
    }
    
        public void panelComprobacion(boolean bandera){
        jpanelVerificacion.setEnabled(bandera);
        labelInfo.setEnabled(bandera);
        labela.setEnabled(bandera);
        labelb.setEnabled(bandera);
        labelc.setEnabled(bandera);
        textLadoa.setEnabled(bandera);
        textLadob.setEnabled(bandera);
        textLadoc.setEnabled(bandera);
        buttonOk.setEnabled(bandera);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        comboTriangulos = new javax.swing.JComboBox<>();
        labelMensaje = new javax.swing.JLabel();
        jpanelVerificacion = new javax.swing.JPanel();
        labelInfo = new javax.swing.JLabel();
        textLadoa = new javax.swing.JTextField();
        textLadob = new javax.swing.JTextField();
        textLadoc = new javax.swing.JTextField();
        labela = new javax.swing.JLabel();
        labelb = new javax.swing.JLabel();
        labelc = new javax.swing.JLabel();
        buttonOk = new javax.swing.JButton();
        buttonOk1 = new javax.swing.JButton();
        panelTriangulo2 = new javax.swing.JPanel();
        labelBaseTriangulo2 = new javax.swing.JLabel();
        labelAlturaTriangulo2 = new javax.swing.JLabel();
        textBaseTriangulo2 = new javax.swing.JTextField();
        textAlturaTriangulo2 = new javax.swing.JTextField();
        panelCuadrado = new javax.swing.JPanel();
        textLado1 = new javax.swing.JTextField();
        labelLado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        textLado2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textLado3 = new javax.swing.JTextField();
        panelCirculo = new javax.swing.JPanel();
        labelRadio = new javax.swing.JLabel();
        textRadio = new javax.swing.JTextField();
        panelRectangulo = new javax.swing.JPanel();
        labelBaseRectangulo = new javax.swing.JLabel();
        labelAlturaRectangulo = new javax.swing.JLabel();
        textBaseRectangulo = new javax.swing.JTextField();
        textAlturaRectangulo = new javax.swing.JTextField();
        buttonCalcular = new javax.swing.JButton();
        textRespuesta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTitulo.setText("TRIANGULOS");

        comboTriangulos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelMensaje.setText("Seleccione el triangulo que desea usar:");

        jpanelVerificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelInfo.setText("Ingrese los tres lados del triangulo seleccionado");

        labela.setText("lado a");

        labelb.setText("lado b");

        labelc.setText("lado c");

        buttonOk.setText("OK");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelVerificacionLayout = new javax.swing.GroupLayout(jpanelVerificacion);
        jpanelVerificacion.setLayout(jpanelVerificacionLayout);
        jpanelVerificacionLayout.setHorizontalGroup(
            jpanelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelVerificacionLayout.createSequentialGroup()
                .addGroup(jpanelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelVerificacionLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jpanelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(textLadoa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labela))
                        .addGap(41, 41, 41)
                        .addGroup(jpanelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textLadob)
                            .addComponent(labelb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jpanelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelc)
                            .addComponent(textLadoc, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(jpanelVerificacionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelInfo)))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelVerificacionLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonOk)
                .addGap(111, 111, 111))
        );
        jpanelVerificacionLayout.setVerticalGroup(
            jpanelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelVerificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jpanelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labela)
                    .addComponent(labelb)
                    .addComponent(labelc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpanelVerificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLadob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLadoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textLadoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonOk)
                .addGap(8, 8, 8))
        );

        buttonOk1.setText("OK");
        buttonOk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOk1ActionPerformed(evt);
            }
        });

        panelTriangulo2.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel-Triangulo"));
        panelTriangulo2.setMinimumSize(new java.awt.Dimension(100, 100));
        panelTriangulo2.setPreferredSize(new java.awt.Dimension(134, 157));

        labelBaseTriangulo2.setText("Base:");

        labelAlturaTriangulo2.setText("Altura:");

        javax.swing.GroupLayout panelTriangulo2Layout = new javax.swing.GroupLayout(panelTriangulo2);
        panelTriangulo2.setLayout(panelTriangulo2Layout);
        panelTriangulo2Layout.setHorizontalGroup(
            panelTriangulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTriangulo2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTriangulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlturaTriangulo2)
                    .addComponent(labelBaseTriangulo2))
                .addGap(18, 18, 18)
                .addGroup(panelTriangulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textBaseTriangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAlturaTriangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelTriangulo2Layout.setVerticalGroup(
            panelTriangulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTriangulo2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelTriangulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBaseTriangulo2)
                    .addComponent(textBaseTriangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelTriangulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlturaTriangulo2)
                    .addComponent(textAlturaTriangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelCuadrado.setBorder(javax.swing.BorderFactory.createTitledBorder("Triángulo Rectángulo"));

        labelLado.setText("Lado:");

        jLabel1.setText("Lado:");

        jLabel2.setText("Lado:");

        javax.swing.GroupLayout panelCuadradoLayout = new javax.swing.GroupLayout(panelCuadrado);
        panelCuadrado.setLayout(panelCuadradoLayout);
        panelCuadradoLayout.setHorizontalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCuadradoLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(labelLado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textLado1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textLado2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCuadradoLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textLado3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCuadradoLayout.setVerticalGroup(
            panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuadradoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textLado2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textLado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        panelCirculo.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel-Circulo"));
        panelCirculo.setMinimumSize(new java.awt.Dimension(100, 100));
        panelCirculo.setPreferredSize(new java.awt.Dimension(134, 157));

        labelRadio.setText("Radio:");

        javax.swing.GroupLayout panelCirculoLayout = new javax.swing.GroupLayout(panelCirculo);
        panelCirculo.setLayout(panelCirculoLayout);
        panelCirculoLayout.setHorizontalGroup(
            panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCirculoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(textRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelCirculoLayout.setVerticalGroup(
            panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCirculoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelRadio)
                    .addComponent(textRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRectangulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Panel-Rectangulo"));
        panelRectangulo.setMinimumSize(new java.awt.Dimension(100, 100));
        panelRectangulo.setPreferredSize(new java.awt.Dimension(134, 157));

        labelBaseRectangulo.setText("Base:");

        labelAlturaRectangulo.setText("Altura:");

        javax.swing.GroupLayout panelRectanguloLayout = new javax.swing.GroupLayout(panelRectangulo);
        panelRectangulo.setLayout(panelRectanguloLayout);
        panelRectanguloLayout.setHorizontalGroup(
            panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectanguloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRectanguloLayout.createSequentialGroup()
                        .addComponent(labelBaseRectangulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textBaseRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRectanguloLayout.createSequentialGroup()
                        .addComponent(labelAlturaRectangulo)
                        .addGap(18, 18, 18)
                        .addComponent(textAlturaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelRectanguloLayout.setVerticalGroup(
            panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRectanguloLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelBaseRectangulo)
                    .addComponent(textBaseRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlturaRectangulo)
                    .addComponent(textAlturaRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonCalcular.setText("Calcular");
        buttonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalcularActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelTitulo)
                    .addComponent(labelMensaje))
                .addGap(18, 18, 18)
                .addComponent(comboTriangulos, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(buttonOk1)
                .addGap(132, 132, 132))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpanelVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(panelCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(panelTriangulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(buttonCalcular)
                .addGap(35, 35, 35)
                .addComponent(textRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboTriangulos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMensaje)
                    .addComponent(buttonOk1))
                .addGap(18, 18, 18)
                .addComponent(jpanelVerificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(panelTriangulo2, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(panelRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                    .addComponent(panelCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCalcular)
                    .addComponent(textRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
        String figuraFiltrada = (String) comboTriangulos.getSelectedItem();
        if( figuraFiltrada.equals("Rectangulo")){
            
            
        String a = textLadoa.getText();
        String b = textLadob.getText();
        String c = textLadoc.getText();
               
        double adouble = Double.parseDouble(a);
        double bdouble = Double.parseDouble(b);
        double cdouble = Double.parseDouble(c);
        
        //a+b>c
        //b+c>a  
        //a+c>b
                
        if(adouble + bdouble > cdouble ){
            
      int iconoAviso = JOptionPane.INFORMATION_MESSAGE;
      JOptionPane.showMessageDialog(rootPane, "Si es triangulo ", "AVISO", iconoAviso);
      
        }else if (bdouble + cdouble > adouble){
            
      int iconoAviso = JOptionPane.INFORMATION_MESSAGE;
      JOptionPane.showMessageDialog(rootPane, "Si es triangulo ", "AVISO", iconoAviso);
      
            
        }else if ( adouble + cdouble > bdouble   ){
            
      int iconoAviso = JOptionPane.INFORMATION_MESSAGE;
      JOptionPane.showMessageDialog(rootPane, "Si es triangulo ", "AVISO", iconoAviso);

        }
        
        }         
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonOk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOk1ActionPerformed
        // TODO add your handling code here:
        
         String figuraFiltrada = (String) comboTriangulos.getSelectedItem();
        if( figuraFiltrada.equals("Rectangulo") ||  figuraFiltrada.equals("Escaleno") || figuraFiltrada.equals("Isosceles") || figuraFiltrada.equals("Equilatero")){
            
            
            panelComprobacion(true);
            
            
        }
    }//GEN-LAST:event_buttonOk1ActionPerformed

    private void buttonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalcularActionPerformed
        // TODO add your handling code here:
        
         if(siEsTriangulo == true){
            
            String itemSeleccionado = (String) comboTriangulos.getSelectedItem();
            if(itemSeleccionado.equals("Rectángulo")){
                
                String lado1 = textLado1.getText();
                String lado2 = textLado2.getText();
                String lado3 = textLado3.getText();
                
                double lado1Double = Double.parseDouble(lado1);
                double lado2Double = Double.parseDouble(lado2);
                double lado3Double = Double.parseDouble(lado3);

                figuras mifigura = new Rectangulo(lado1Double,lado2Double, lado3Double );
                
                System.out.println("Area del triangulo rectangulo: "+mifigura.calcularArea());
                System.out.println("Permietro del triangulo rectangulo: "+mifigura.calcularPerimetro());
                System.out.println("Altura del triangulo rectangulo: "+mifigura.calcularAltura());
                
                
            }else if(itemSeleccionado.equals("Isóceles")){
               
                
                
                
            }else if(itemSeleccionado.equals("Escaleno")){
               
                
                
            }else if(itemSeleccionado.equals("Equilátero")){
                
                /*Figuras f = new Triangulo(4,2); //Para calcilar Area
                f.calcularArea();
                f.calcularPerimetro();*/
                
            }
            
        }
        
    }//GEN-LAST:event_buttonCalcularActionPerformed

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIExamen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIExamen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCalcular;
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton buttonOk1;
    private javax.swing.JComboBox<String> comboTriangulos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jpanelVerificacion;
    private javax.swing.JLabel labelAlturaRectangulo;
    private javax.swing.JLabel labelAlturaTriangulo;
    private javax.swing.JLabel labelAlturaTriangulo1;
    private javax.swing.JLabel labelAlturaTriangulo2;
    private javax.swing.JLabel labelBaseRectangulo;
    private javax.swing.JLabel labelBaseTriangulo;
    private javax.swing.JLabel labelBaseTriangulo1;
    private javax.swing.JLabel labelBaseTriangulo2;
    private javax.swing.JLabel labelInfo;
    private javax.swing.JLabel labelLado;
    private javax.swing.JLabel labelMensaje;
    private javax.swing.JLabel labelRadio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labela;
    private javax.swing.JLabel labelb;
    private javax.swing.JLabel labelc;
    private javax.swing.JPanel panelCirculo;
    private javax.swing.JPanel panelCuadrado;
    private javax.swing.JPanel panelRectangulo;
    private javax.swing.JPanel panelTriangulo;
    private javax.swing.JPanel panelTriangulo1;
    private javax.swing.JPanel panelTriangulo2;
    private javax.swing.JTextField textAlturaRectangulo;
    private javax.swing.JTextField textAlturaTriangulo;
    private javax.swing.JTextField textAlturaTriangulo1;
    private javax.swing.JTextField textAlturaTriangulo2;
    private javax.swing.JTextField textBaseRectangulo;
    private javax.swing.JTextField textBaseTriangulo;
    private javax.swing.JTextField textBaseTriangulo1;
    private javax.swing.JTextField textBaseTriangulo2;
    private javax.swing.JTextField textLado1;
    private javax.swing.JTextField textLado2;
    private javax.swing.JTextField textLado3;
    private javax.swing.JTextField textLadoa;
    private javax.swing.JTextField textLadob;
    private javax.swing.JTextField textLadoc;
    private javax.swing.JTextField textRadio;
    private javax.swing.JTextField textRespuesta;
    // End of variables declaration//GEN-END:variables
}
